on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-18.04]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2
      with:
         path: './src/github.com/kevinburke/go-bindata'
    - name: change permissions on meterbin
      run: sudo mkdir -p /usr/local/meter/bin && sudo chown runner:runner /usr/local/meter/bin
    - uses: actions/cache@v2
      with:
        path: /usr/local/meter/bin
        key: ${{ runner.os }}-meterbin-v3-${{ hashFiles('./src/github.com/kevinburke/go-bindata/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-meterbin-v3-
    - uses: actions/cache@v2
      with:
        path: /home/runner/.cache
        key: ${{ runner.os }}-go-v3-${{ hashFiles('**/*.go') }}
        restore-keys: |
          ${{ runner.os }}-go-v3-
    # staticcheck needs this for GOPATH
    - run: |
        echo "GOPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/bin:$PATH" >> $GITHUB_ENV
        echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
    - name: Download dependencies
      run: go get -t -v ./...
      working-directory: './src/github.com/kevinburke/go-bindata'
    - name: Run tests
      run: make ci
      working-directory: './src/github.com/kevinburke/go-bindata'
